<#
.SYNOPSIS
Format a release readiness summary JSON into a PR-ready markdown snippet.

.DESCRIPTION
This utility reads the machine-readable release readiness summary generated by
Invoke-AITestPilotReleaseReadinessReport.ps1 and renders a compact, copy/paste-ready
markdown block for PR descriptions or milestone comments.

.PARAMETER SummaryJson
Path to Temp\release-readiness-summary.json by default.

.PARAMETER OutputPath
Optional output path. If omitted, prints markdown block to the console.

.PARAMETER IncludeFailedOnly
When set, include only non-passing checks instead of all checks.

.PARAMETER SnippetOutputPath
Optional output path for an independently written snippet file (independent from OutputPath).
#>
[CmdletBinding()]
param(
    [string]$SummaryJson = "Temp\release-readiness-summary.json",
    [string]$OutputPath = "",
    [switch]$IncludeFailedOnly,
    [string]$SnippetOutputPath = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

function Resolve-PathUnderRepo {
    param([string]$Path)
    return [System.IO.Path]::GetFullPath((Join-Path $repoRoot $Path))
}

function Format-CheckLine {
    param(
        [string]$Label,
        [string]$Status,
        [string]$Detail
    )
    $icon = switch ($Status) {
        "PASS" { "x" }
        "WARN" { "!" }
        default { " " }
    }

    $suffix = ""
    if (-not [string]::IsNullOrWhiteSpace($Detail)) {
        $suffix = " ($Detail)"
    }

    return "- [$icon] $Label$suffix"
}

$summaryPath = Resolve-PathUnderRepo $SummaryJson
if (-not (Test-Path $summaryPath)) {
    throw "Readiness summary not found: $summaryPath"
}

try {
    $raw = Get-Content -Path $summaryPath -Raw -Encoding UTF8 | ConvertFrom-Json -ErrorAction Stop
}
catch {
    throw "Failed to parse readiness summary '$summaryPath': $($_.Exception.Message)"
}

$gateStatus = [string]$raw.gate_status
$counts = $raw.counts
$passCount = if ($counts -and $counts.PSObject.Properties["pass"]) { [int]$counts.pass } else { 0 }
$warnCount = if ($counts -and $counts.PSObject.Properties["warn"]) { [int]$counts.warn } else { 0 }
$failCount = if ($counts -and $counts.PSObject.Properties["fail"]) { [int]$counts.fail } else { 0 }
$blockingCount = if ($counts -and $counts.PSObject.Properties["blocking"]) { [int]$counts.blocking } else { 0 }
$requirePipeline = [bool]$raw.require_release_pipeline
$failOnWarning = [bool]$raw.fail_on_warning
$checks = @()
if ($null -ne $raw.checks) { $checks = @($raw.checks) }

$lines = @(
    "## Release readiness summary",
    "",
    "- Gate status: **$gateStatus**",
    "- PASS: $passCount",
    "- WARN: $warnCount",
    "- FAIL: $failCount",
    "- Blocking: $blockingCount",
    "- RequireReleasePipeline: $requirePipeline",
    "- FailOnWarning: $failOnWarning",
    "",
    "### Checks"
)

foreach ($check in $checks) {
    if ($null -eq $check) { continue }
    $status = if ($check.PSObject.Properties["status"]) { [string]$check.status } else { "FAIL" }
    if ($IncludeFailedOnly -and $status -eq "PASS") { continue }

    $label = if ($check.PSObject.Properties["label"]) { [string]$check.label } else { "unknown" }
    $detail = if ($check.PSObject.Properties["detail"]) { [string]$check.detail } else { "" }
    $lines += Format-CheckLine -Label $label -Status $status -Detail $detail
}

if ($IncludeFailedOnly -and ($lines.Count -le 9)) {
    $lines += "- No failed or warning checks."
}

$text = $lines -join [Environment]::NewLine

if (-not [string]::IsNullOrWhiteSpace($OutputPath)) {
    $outputFull = Resolve-PathUnderRepo $OutputPath
    $outputDir = Split-Path $outputFull -Parent
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
    }
    Set-Content -Path $outputFull -Encoding UTF8 -Value $text
    Write-Output "Release readiness snippet: $outputFull"
} else {
    Write-Output $text
}

if (-not [string]::IsNullOrWhiteSpace($SnippetOutputPath)) {
    $snippetOutputFull = Resolve-PathUnderRepo $SnippetOutputPath
    $snippetOutputDir = Split-Path $snippetOutputFull -Parent
    if (-not (Test-Path $snippetOutputDir)) {
        New-Item -ItemType Directory -Force -Path $snippetOutputDir | Out-Null
    }
    Set-Content -Path $snippetOutputFull -Encoding UTF8 -Value $text
    Write-Output "Release readiness snippet (file): $snippetOutputFull"
}
